### ISSUE TITLE
Doesn't scrobble movies

### ISSUE THREAD

**Issue by grepole121** [XaF/TraktForVLC#1]
I have installed TraktForVLC and it works fine for TV shows but when I watch a movie it doesn't work. In the config.ini file I have set it to yes for everything. The file format is MovieName (year) for example Dumb & Dumber (1994)

**Comment by XaF** [comment]
Can you start TraktForVLC using the following command:

```bash
python TraktForVLC.py --debug --small-timers
```

And provide the resulting log file?
It should be named ```TraktForVLC-DEBUG.log``` and be in the ```logs``` directory near TraktForVLC.py (except if you have specified another data directory using the --datadir option). It should give me the information needed to understand the origin of your problem.

**Comment by grepole121** [comment]
Log File: http://pastebin.com/18huS7u2

**Comment by XaF** [comment]
Thanks for the report!
I missed a variable change in a previous modification. Movies were found but didn't match the time of the vlc-opened file as it was refering to an unexisting variable.
