### ISSUE TITLE
Failing to install on El Capitan

### ISSUE THREAD

**Issue by kerstin** [XaF/TraktForVLC#102]
Hey, I was going to try out the new TraktForVLC but sadly can't get it to work.

The error I'm getting is the following:
```
Error loading Python lib '/var/folders/1n/3wtjnjvn6332d4spd154zqyh0000gn/T/_MEIFYn1kk/.Python': dlopen: dlopen(/var/folders/1n/3wtjnjvn6332d4spd154zqyh0000gn/T/_MEIFYn1kk/.Python, 10): Symbol not found: _getentropy
  Referenced from: /var/folders/1n/3wtjnjvn6332d4spd154zqyh0000gn/T/_MEIFYn1kk/.Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/1n/3wtjnjvn6332d4spd154zqyh0000gn/T/_MEIFYn1kk/.Python
```

Some quick googling for `/usr/lib/libSystem.B.dylib` led me to other people's issues with installing Ruby, which could be fixed with Xcode installs or updates. My Xcode is up-to-date, however.

This is happening on Mac OS X El Capitan 10.11.6 with system Python. Tried using TraktForVLC_2.0.0a2_osx as well as the latest version (TraktForVLC_2.0.0a2.dev6.ga58c2f9_osx) following the instructions in the README. Have yet to try it on a newer MacOS.

**Comment by XaF** [comment]
The legacy version of the macOS bien should work for you.
