### ISSUE TITLE
error of field 'delay'

### ISSUE THREAD

**Issue by danteali** [XaF/TraktForVLC#103]
>lua error: Error loading script C:\Program Files\VideoLAN\VLC\lua\intf\trakt.luac: trakt.lua:2170: attempt to perform arithmetic on field 'delay' (a nil value)

On watching movies in Windows 10.  TV seems to be okay for some reason. But not certain its limited to movies, thats just when I've been able to replicate it.
All versions released so far.
Seems to be triggered when I skip forward in the video. At least that's how I can trigger the error immediately.

Not sure if this is the reason why my movies are not being sent to trakt. All TV seems to make it to Trakt but never movies.

**Comment by XaF** [comment]
Thank you for the report.
This bug should only appear when you already scrobbled a media once and are trying to scrobble it again. The delay between scrobbles is a configuration option (media/stop/delay) that I forgot to add to the configuration options creation.

I'll deploy a patch for that soon.

**Comment by danteali** [comment]
Thanks. 

After this error appears, it seems to stop TraktforVLC doing any additional analysis. If I start another video, I don't see any other messages appearing and subsequent videos don't get synced with Trakt. It starts working again if I start a fresh VLC session.

**Comment by XaF** [comment]
This is normal, it fails the lua script and thus stop executing it entirely.
