### ISSUE TITLE
issue over osx 10.10.4

### ISSUE THREAD

**Issue by devilsoulblack** [XaF/TraktForVLC#11]
Alfredo-Andaluz-Prados-MacBook-Pro:~ aandaluz$ python TraktForVLC.py 
Traceback (most recent call last):
  File "TraktForVLC.py", line 41, in <module>
    import requests
ImportError: No module named requests
Alfredo-Andaluz-Prados-MacBook-Pro:~ aandaluz$

**Comment by XaF** [comment]
* What python version are you using ? ```python --version```
* Have you the ```requests``` directory besides the ```TraktForVLC.py``` file ?

**Comment by devilsoulblack** [comment]
Hi XaF

Python 2.7.6

Yes i have requests file outside directory

**Comment by XaF** [comment]
Can you go to your ```TraktForVLC``` directory in a console and run:
```sh
python -c "import os; print(os.listdir('.')); import requests; print(dir(requests))"
```

And past here the result ? Thanks.

**Comment by devilsoulblack** [comment]
Hi Xaf, the TraktForVLC is on /Users/aandaluz

and this is the result 


Alfredo-Andaluz-Prados-MacBook-Pro:~ aandaluz$ python -c "import os; print(os.listdir('.')); import requests; print(dir(requests))"
['.adobe', '.atom', '.bash_history', '.bi_li3', '.ccnet', '.CFUserTextEncoding', '.config', '.cups', '.DownloadManager', '.dropbox', '.DS_Store', '.filezilla', '.gnupg', '.htoprc', '.jmf', '.local', '.magicJack', '.mplayer', '.nchsoftware', '.prism', '.putty', '.rnd', '.shsh', '.smb', '.spumux', '.ssh', '.subversion', '.Trash', '.viminfo', '.vnc', '.Xauthority', '.xchat2', '1', '130680801', '130680801.zip', '20110323.txt', '936835-2015-03-10.hrf', 'Applications', 'backup_cabina', 'bin', 'debian-7.3.0-amd64-CD-1.iso', 'Desktop', 'Documents', 'Downloads', 'Dropbox', 'Google Drive', 'HOGAR_REP_CL_2014-09-02_r9.csv', 'imap.txt', 'Library', 'licitacion1.xml', 'licitacion1.xsl', 'licitacio\xcc\x81n1.css', 'MALWARE.php', 'Movies', 'Music', 'ownCloud', 'Pictures', 'Public', 'reportes', 'Seafile', 'Sites', 'Spark', 'TraktForVLC.py', 'virus.php', 'wolfip', '~$DIMENSIONAMIENTO.xlsx']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named requests
Alfredo-Andaluz-Prados-MacBook-Pro:~ aandaluz$ 

Regards

**Comment by XaF** [comment]
Ok, it seems your installation of TraktForVLC is wrong.
Can you please download it (for instance [from here](https://github.com/XaF/TraktForVLC/archive/v1.3.0-rc1.zip)) and extract all the files to a directory (for instance ```/Users/aandaluz/TraktForVLC```). You should then be able to run the Python command I gave you from this directory. It should nove give any error, and thus ```TraktForVLC``` should work!

**Comment by devilsoulblack** [comment]
XaF

i download the file you say but i get this message 

Alfredo-Andaluz-Prados-MacBook-Pro:TraktForVLC aandaluz$ python TraktForVLC.py 
/Users/aandaluz/TraktForVLC/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by XaF** [comment]
It's just a warning so ```TraktForVLC``` should be working.
If you want it to disappear, I suggest upgrading your Python version to 2.7.9 or installing pyopenssl (using pip: ```pip install pyopenssl```).
