### ISSUE TITLE
how to uninstall TraktForVLC

### ISSUE THREAD

**Issue by Han9402** [XaF/TraktForVLC#112]
I had install the TraktForVLC  in my ubuntu laptop, the message often stop video playback and effect me. How to uninstall it?

OS: Ubuntu 18.04 LTS
VLC: 4.0.0-dev Otto Chriek
TraktForVLC: 2.0.0a2.dev14.g31faf4b_linux

the message:
TraktForVLC is not setup with Trakt.tv yet!
--
PLEASE GO TO https://trakt.tv/activate
AND ENTER THE FOLLOWING CODE:
xxxxxxxx

**Comment by XaF** [comment]
`TraktForVLC` is showing that message as it is not enabled on your trakt.tv account. As soon as it is, this message will stop showing.

However, if you really want to uninstall, you can just run `TraktForVLC_<version>_<os> uninstall`

**Comment by Han9402** [comment]
thx

**Comment by kneelesh48** [comment]
What do I do for windows?

**Comment by AdrianStone0405** [comment]
> What do I do for windows?

I don't know, I just re-install it in ubuntu and fix it.
