### ISSUE TITLE
Movie not recognized, only TV

### ISSUE THREAD

**Issue by batfos** [XaF/TraktForVLC#119]
I just updated to the latest (2.0.0a2.dev18+g9b9d57c) and now movies (and anime series) not recognized, only TV. I checked in the trakt_cache file, there is no IMDb information except for TV shows. With the previous release it was working fine. I try renaming the files but still not working.

**Comment by XaF** [comment]
Hi,

Can you please provide a log file in debug mode?

Thanks!

**Comment by batfos** [comment]
Is it the right file?
[log.txt](https://github.com/XaF/TraktForVLC/files/2113994/log.txt)

**Comment by batfos** [comment]
Thank you!

**Comment by ac96789** [comment]
Just a quick question @XaF , once you've applied the patch.. How do we update?

**Comment by XaF** [comment]
Once the patch will be applied, you can just install the new version of TraktForVLC over the previous one. It will automatically uninstall the previous one and install the new one. If there is any problem during that process, please report with all of the details so I can try and fix it :)
