### ISSUE TITLE
No permission to write pidfile

### ISSUE THREAD

**Issue by irpl** [XaF/TraktForVLC#13]
Running the script in DEBUG mode always seems to work fine. When trying to execute it manually with the following line 
`python TraktForVLC.py --datadir "C:\Users\User\Documents\TraktForVLC-master" --config "C:\Users\user\Documents\TraktForVLC-master" --pidfile "C:\Users\user\Documents\TraktForVLC-master"`

I get this error from python

Traceback (most recent call last):
  File "TraktForVLC.py", line 871, in <module>
    file(pidfile, "w").write("%s\n" % str(os.getpid()))
IOError: [Errno 13] Permission denied: 'C:\\Users\\user\\Documents\\TraktForVLC-master'

any ideas why?

cheers

**Comment by XaF** [comment]
The ```--pidfile``` option actually takes a file and not a directory.
Try with:
```sh
python TraktForVLC.py --datadir "C:\Users\User\Documents\TraktForVLC-master" --config "C:\Users\user\Documents\TraktForVLC-master" --pidfile "C:\Users\user\Documents\TraktForVLC-master\TraktForVLC.pid"
```

**Comment by irpl** [comment]
Great! Thanks. that fixed that problem, now I'm getting this message

C:\Python27\lib\site-packages\pkg_resources\__init__.py:197: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is
 a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary.
 For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setupto
ols project describing that need.
  stacklevel=1,

how might I fix this?

**Comment by irpl** [comment]
Great! Thanks. That fixed that problem but now I'm get this message

C:\Python27\lib\site-packages\pkg_resources\__init__.py:197: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is
 a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary.
 For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setupto
ols project describing that need.
  stacklevel=1,


how might I fix this?

**Comment by irpl** [comment]
Though it seems to be working as it should, was just wondering if the message above means anything to me concerned about.

**Comment by XaF** [comment]
Yes, it is just a warning, so it won't prevent TraktForVLC to work.
Thank you to signal it though, I'll patch it for the next series of commits!

**Comment by irpl** [comment]
Thanks a lot for your help!
