### ISSUE TITLE
Can't get it to work on OSX

### ISSUE THREAD

**Issue by alltimemarr** [XaF/TraktForVLC#14]
Hello,

I tried doing this on Mac, but I cannot seem to get it to work.

I changed the settings in VLC. Changed the oldrc to rc too. So far so good. But as soon as I close the app, and open it again, the settings are gone. The localhost:4222 line, and the remote control selection. However, "rc" remains to be there in that line. I do not know if that is the big problem, but well... might have something to do with it.

Configuring part was all good. As far as I know, but I did not get the automatic start with plist file. I did everything there, I guess, but I am a total noob with all that fancy stuff.

I downloaded Python 2.7.6, and installed it, I do not know what to do with it, if I need to do anything with it at all, but I put the location path in the plist file (I think!!), and also the other paths.

This is how my plist file looks now:
http://pastebin.com/j03PDcCE

I put that file in the library mentioned.

After that I opened Terminal and tried to load that file, with the command line listed.
launchctl load ~/Library/LaunchAgents/org.TraktForVLC.plist

Nothing happened, I did not see anything, and I read somewhere before that you could check if it was done correctly via launchctl list. Seems like /something/ went wrong, because I searched for Trakt but found nothing.

Could someone be kind enough to guide me through this?
If you need any more information, please ask! :)

**Comment by XaF** [comment]
##### For VLC
Save the parameters as they should be. Close VLC and reopen it. Don't open the parameters again but just try the following command in a console (considering you use the 4222 port in the configuration of VLC):
```sh
telnet localhost 4222
```
What does it say?

##### For ```.plist```
It seems that the path ```/Library/Frameworks/Python.framework/Versions/3.4``` you provide as your path to python is wrong, as it should be the path to the python executable file (usually called python). Is there a ```python``` file in this path? If so, adds ```/python``` at the end. You could also be sure of that path using the ```which python``` command if it works on Mac. I'm not myself a Mac user, some some nice other users of ```TraktForVLC``` gave me in #7 the information to provide a way for Mac users to automatize the execution.

##### For ```TraktForVLC```
If the previous step doesn't help, you should also be able to verify if ```TraktForVLC``` works properly using the debug mode:
```sh
./TraktForVLC.py --debug --small-timers
```
And then looking at the generated ```TraktForVLC-DEBUG.log``` file that should be in the ```logs/``` directory. You could then provide that file!

**Comment by alltimemarr** [comment]
Thanks for your fast response :)

This is what the Terminal says after putting in that command telnet localhost 4222
"Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying fe80::1...
telnet: connect to address fe80::1: Connection refused
telnet: Unable to connect to remote host"

---

Oh, the path is wrong indeed. I did which python, and it gave me: "/usr/bin/python" Seems like Mac already has a built-in Python! Great, than I can remove that Python stuff I installed, haha.

THANKS! That did the trick! I now have "96434	0	org.user.TraktForVLC" in the launchctl list command response thing! :)

---

Then I tried to play some files to test scrobbling, but I saw nothing, so it seems my settings in VLC are indeed wrong.
Here are some settings or how it all looks;
http://prntscr.com/74glzq
http://prntscr.com/74gmh4

(it's Dutch, yeah sorry D:)

**Comment by alltimemarr** [comment]
Oh, and i did not get a long file, but I copied the stuff I saw in the Terminal:

http://pastebin.com/sFfLpwnf

I them put in the command on the last line with a date and stuff, but got some sort of error:
/Applications/VLC.app/Contents/MacOS/vlc --extraintf=rc --rc-host=localhost:4222 --rc-quiet

And it returned the following:
VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1-0-ga425c42)
vlc: unknown option or missing mandatory argument `--rc-host=localhost:4222'
Try `vlc --help' for more information.

**Comment by XaF** [comment]
Ok, so it's normal that ```TraktForVLC``` isn't scrobbling anything as it is unable to connect to VLC (like the telnet told us). Your last command also gives us an idea of the problem, but I'm kind of lost as it should work on MacOS too.

Could you try the following command?
```sh
vlc --extraintf=oldrc --rc-host=localhost:4222
```
What does it say?

If it seems to work and open VLC, could you try again the ```telnet localhost 4222``` ?

```oldrc``` is not the best choice, but it should still work (I made ```TraktForVLC``` as compatible for ```rc``` and ```oldrc``` as possible).

Also, sorry for the logfile, it's true that I changed the default behavior of ```TraktForVLC``` to show the log in the console if you don't specify a logfile and are not in daemon mode but I quite forgot because of habit! So that was normal, my mistake!

**Comment by alltimemarr** [comment]
No problem! :) I am just glad you are trying to help me! You're doing a great job! Don't worry about it.

I entered the command vlc --extraintf=oldrc --rc-host=localhost:4222, but it did not do anything, it did not work.
"-bash: vlc: command not found"

I am not as smart as to know what that means (the bash part), but I then tried to use the path/executeable file path instead of just VLC, and that did work, but it gave the same error as mentioned earlier,

Entered this: /Applications/VLC.app/Contents/MacOS/vlc --extraintf=oldrc --rc-host=localhost:4222
Returned: VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1-0-ga425c42)
vlc: unknown option or missing mandatory argument `--rc-host=localhost:4222'
Try `vlc --help' for more information.


Then I just kinda went my own way, and tried to put the first part of the command and the last part separately.
Entered this: /Applications/VLC.app/Contents/MacOS/vlc --extraintf=oldrc
Returned: VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1-0-ga425c42)
[0000000100408d08] core libvlc error: No plugins found! Check your VLC installation.

Does this mean there is something wrong with my installation? Or is it just because i tried to split the command to two separate instead of putting it in one line. If you know what I mean :-P

**Comment by XaF** [comment]
For your last command, did the message end there or did you have more text after? (after you typed ```/Applications/VLC.app/Contents/MacOS/vlc --extraintf=oldrc```)

Ok, can you do the following commands and give me what they return?
* ```echo $VLC_PLUGIN_PATH```
* ```ls /usr/lib | grep vlc```
* ```ls /usr/local/lib | grep vlc```

**Comment by alltimemarr** [comment]
No, it was all I typed:
http://prntscr.com/74vox9

echo $VLC_PLUGIN_PATH
returns nothing, a white line.

ls /usr/lib | grep vlc
also returns nothing, but it doesn't give me a white line, does it do something in the background?


ls /usr/local/lib | grep vlc
returns ls: /usr/local/lib: No such file or directory

**Comment by XaF** [comment]
Ok, that should be verbal but, can you try this:
```sh
ls -AlsR /Applications/VLC.app/Contents/MacOS/
```

Perhaps I'm mistaken on the path, remember I don't have nor ever used OSX. In such case, find a ```VLC.app``` directory, and look up if there's a ```Contents/MacOS/``` subdirectory. If so, do that command on that directory. If you just find the ```VLC.app``` directory, do the command on it, to see if we can find something that works from here...

**Comment by XaF** [comment]
Has this issue been solved?

**Comment by indastoop** [comment]
I'm having the exact same responses to every steps alltimemarr did here.
And to the last line (for which the path seems right),
<pre>ls -AlsR /Applications/VLC.app/Contents/MacOS/</pre>
Here is what it responds:
http://pastebin.com/YcVKypGb
If it helps you understand what's happening, and if you have a little time to spare to this issue, I'd gladly hear your advices

**Comment by indastoop** [comment]
if it helps, here is also the result log from the
<pre>./TraktForVLC.py --debug --small-timers</pre>
http://pastebin.com/XZjmFcg8

**Comment by XaF** [comment]
@indastoop Actually, your `TraktForVLC` log file says that everything is working fine for you! @alltimemarr was having problems with VLC directly, that didn't find it's remote control plugin, preventing VLC and `TraktForVLC` to communicate. In your case, `TraktForVLC` identified that you were watching Game of Thrones 5x01 and set it as watching on Trakt. It didn't scrobble yet as you were only at 22% of it.

**Comment by indastoop** [comment]
thanks for your answer, I thought the response to <code>./TraktForVLC.py --debug --small-timers</code> was kind of erratic... my track.tv account isn't updating though, even after watching the whole epidose. since I have troubles with my internet connection, I'll try to sort this TraktForVLC out after my provider has resolved things here.
anyway, thanks again for this page!

**Comment by XaF** [comment]
@indastoop Yeah, currently TraktForVLC only works in online mode, which is kind of a big limit even if we're usually connected most of the time. I plan on making an offline watching support in future versions. It's in the next things I want to do on my pipeline and should be appearing by the end of summer if I find the time to work on it!

**Comment by AlessandroDallafina** [comment]
Hi XaF, I've followed your suggestions and debugged everything correctly. It seems I'm getting data but I'm not sure why It doesn't appear in my tracktv history. I tried many known movies and TV series episodes but I always see `No tv show nor movie found for the current playing `. 
Here's part of the the verbose output. 

 ```2015-10-24 21:33:28,467::VLCRemote::DEBUG::<- Received: VLC media player 2.2.1 Terry Pratchett (Weatherwax)
Command Line Interface initialized. Type `help' for help.
>
2015-10-24 21:33:28,467::VLCRemote::DEBUG::-> Sending: is_playing
2015-10-24 21:33:28,467::VLCRemote::DEBUG::<- Received: 1
2015-10-24 21:33:28,467::VLCRemote::DEBUG::cleaning cache
2015-10-24 21:33:28,467::VLCRemote::DEBUG::<- Received: >
2015-10-24 21:33:28,468::VLCRemote::DEBUG::-> Sending: get_length
2015-10-24 21:33:28,468::VLCRemote::DEBUG::<- Received: 1282
2015-10-24 21:33:28,468::VLCRemote::DEBUG::cleaning cache
2015-10-24 21:33:28,468::VLCRemote::DEBUG::<- Received: >
2015-10-24 21:33:28,468::VLCRemote::DEBUG::-> Sending: get_title
2015-10-24 21:33:28,468::VLCRemote::DEBUG::<- Received: http://127.0.0.1:51735/
2015-10-24 21:33:28,468::VLCRemote::DEBUG::cleaning cache
2015-10-24 21:33:28,469::VLCRemote::DEBUG::<- Received: >
2015-10-24 21:33:28,469::VLCRemote::DEBUG::-> Sending: get_time
2015-10-24 21:33:28,469::VLCRemote::DEBUG::<- Received: 134
2015-10-24 21:33:28,469::TraktForVLC::INFO::No tv show nor movie found for the current playing video```

**Comment by XaF** [comment]
@AlessandroDallafina what is in your config.yml file? Is it always 127.0.0.1:51735 that's appearing on VLC? Are you actually watching something that's streamed from that local address?

**Comment by roelvan** [comment]
I had similar problems, requesting a new PIN did the trick for me.

**Comment by JimiC** [comment]
I have noticed that if you authorize with trakt.tv and you don't connect to trakt.tv with that token, inside a reasonable amount of time, the token gets invalid and trakt APO response with '401 Unauthorized'.

**Comment by PhilDougl** [comment]
Hi.
I have exactly the same problem as "alltimemarr". It seems that his problem was never fixed and the thread went onto talk about other problems or was the problem fixed ?

I have the problem where telnet localhost 4222    fails.  I am using the latest OSX. 
Can anybody help
Thanks

PhilipsMBP-Wifi:MacOS administrator$ telnet localhost 4222
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying fe80::1...
telnet: connect to address fe80::1: Connection refused
telnet: Unable to connect to remote host
PhilipsMBP-Wifi:MacOS administrator$

**Comment by PhilDougl** [comment]
Hi I managed to get the telnet working with ./VLC
administrator$ ./VLC --extraintf=rc --rc-host=localhost:4222
VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1-0-ga425c42)
[0000000100642288] [cli] lua interface: Listening on host "localhost:4222".
[000000010021a3d8] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.

I am now getting this

administrator$ ./TraktForVLC.py --debug --small-timers
Traceback (most recent call last):
  File "./TraktForVLC.py", line 38, in <module>
    from pkg_resources import parse_version
ImportError: No module named pkg_resources
PhilipsMBP-Wifi:TraktForVLC administrator$

**Comment by michalsapka** [comment]
I have the same problem: VLC doesn't save settings after close. I followed @alltimemarr steps and have the same results. Is this problem with VLC on OS X in general?

**Comment by michalsapka** [comment]
Got it fixed by using LUA interface instead or RC.

**Comment by ondrejfuhrer** [comment]
@michalsapka I had the same issue and after changing interface to LUA everything seems to work, thanks :+1:

**Comment by kerstin** [comment]
Thanks for the hints in here about the LUA settings.

Seeing as the problem's been around for a while, I don't understand why this hasn't been addressed in the project's README yet. I don't see less tech-savvy users spending several hours of their time trying to debug plugins like these which aren't easy for them to to install in the first place...

**Comment by XaF** [comment]
Mostly because I haven't had the try to test it

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
