### ISSUE TITLE
Stopping Trakt for VLC when not watching anything?

### ISSUE THREAD

**Issue by GiacomoLaw** [XaF/TraktForVLC#142]
My PC == potato. Therefore, is there any way to automatically stop the process when VLC isn't open, and start it when it is?

Thanks!

**Comment by glensc** [comment]
do you even understand yourself what are you asking?

**Comment by GiacomoLaw** [comment]
Yes - when I close VLC, the plugin still ran when it was actually working...

**Comment by xaf** [comment]
The process does not do anything when VLC is not running. The process is a local server that's only there to listen to requests, and respond to them. If there is no request... It is thus just idling and shouldn't consume much.
It is not possible on Windows to go a different way than having that process running, given that if I tried doing it like I did for linux and macos, you would get a window poping on and off every minute (thanks Windows)

**Comment by GiacomoLaw** [comment]
Great, thank you!
