### ISSUE TITLE
Error during playback, no tracking happens

### ISSUE THREAD

**Issue by Calebzor** [XaF/TraktForVLC#16]
Getting ONLY this error repeated in the log during playback and no tracking occurs:

```
Received: 
2015-05-26 10:20:40,766::VLCRemote::DEBUG::-> Sending: is_playing
2015-05-26 10:20:43,766::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\VLC\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\VLC\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\VLC\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\VLC\TraktForVLC-master\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?
```

I've tried using start_debug_process.bat in hopes for some more debug information, but with no avail.

Any help on tracking down this issue and making the script work would be appreciated.

**Comment by grepole121** [comment]
Update to the most recent version?

**Comment by XaF** [comment]
It seems that following the ```is_playing``` request to VLC remote control ```TraktForVLC``` did not receive anything.
You can start running ```TraktForVLC``` using the ```start_debug_process.bat``` or manually as you pointed you didn't manage to make it work, using the following command:
```sh
C:\path\to\pythonw.exe TraktForVLC.py --debug --small-timers
```

You should then be able to have the full debug log.

Also, could you provide the following information?
* Version of ```TraktForVLC``` (you should be using the last, as mentioned by @grepole121 )
* Version of VLC
* Version of your OS
* Version of Python

Most of those should already be in the DEBUG log that I encourage you to share in full.

**Comment by Calebzor** [comment]
I now made sure I have the latest version. I might have had an older version before, sorry about that.

Running on Windows-7-6.1.7601-SP1, with Python 2.7.9, VLC 2.2.1

This is the full log now: http://pastebin.com/DpcRyS5f

Tracking still does not seem to work. I assume if I seek up to just before 90% of something and start playing from there, it’d get marked as watched, right?

**Comment by XaF** [comment]
The ```0``` answer to ```is_playing``` means nothing is being played in VLC. Are you sure the VLC you're using is the one ```TraktForVLC``` is connected to? ```is_playing``` should be answering ```1``` while you are watching something.

Also, it will not automatically mark as watched after 90%, it verifies that you were watching for a period of time. This prevents marking movies as watched if you were just looking at the quality of it for instance.

**Comment by Calebzor** [comment]
There is only one instance of VLC running. How can I make sure that **TraktForVLC** is properly connected?

**Comment by XaF** [comment]
Well if it wasn't it would have shown a message. Can you play any video file in your VLC and try the telnet connection ?
To do so, open a command prompt window (start menu, accessories, command prompt I think) then run the following:
```sh
pkgmgr /iu:TelnetClient
pkgmgr /iu:TelnetServer
telnet localhost 4222
```

Try then to run ```is_playing``` and  ```get_title```. That will tell us if the remote control works ok. Be sure that ```TraktForVLC``` isn't running during that time!

**Comment by Calebzor** [comment]
telnet did not seem to work from cmd. After connecting nothing I typed showed up, so I tried from cygwin and got the following:
```
$ telnet localhost 4222
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
is_playing
```

Basically nothing happens after inputing the is_playing command.

**Comment by XaF** [comment]
Hm, could you perhaps try to run VLC using the command prompt to be sure it's running with the right parameters ? Just after the connection, VLC should have greeted you.

The command line should look like this:
```sh
C:\path\to\vlc.exe --extraintf=rc --rc-host=localhost:4222
```

Then open another cygwin terminal and run the telnet again. Be sure that there is not any other VLC running, and not any ```TraktForVLC``` running (even in background).
If you want to be sure there isn't any conflict, you can change the port to something *random* like 35678 for instance, in both the command line to start VLC and the following telnet connection. That perhaps will give us more information (VLC could also show interesting information when you start it from command line).

**Comment by Calebzor** [comment]
Let me first just say I really appreciate you taking the time to try and help me.

The port seems to have been the issue, connecting to the rc on a new port like 35678 worked.

Now I started `start_debug_process.bat `  but started getting the same error in the log:

```

Received: 
2015-05-26 18:02:05,585::VLCRemote::DEBUG::-> Sending: is_playing
2015-05-26 18:02:08,585::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\VLC\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\VLC\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\VLC\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\VLC\TraktForVLC-master\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?
```

**Comment by Calebzor** [comment]
Ohh and yes from telnet `is_playing` was returning 1

**Comment by XaF** [comment]
I'm here for that! :)

Ok, what else do you have in the debug log?
Did you try connecting with the telnet on that port and trying the commands? (it is really weird because this is meaning that VLC is not answering again)
Are you sure there is not any other VLC or TraktForVLC running at the same time?

**Comment by XaF** [comment]
Also, just to be sure: did you update the config.bat before running ```start_debug_process.bat``` ?

**Comment by Calebzor** [comment]
Yeah I did update the config. The problem was stuck VLC processes that did not show up at the Applications tab in the Windows Task Manager. Had to kill them from the Processes tab.

I think this is resolved now. Thanks for the help.

**Comment by XaF** [comment]
You're welcome!
