### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by grepole121** [XaF/TraktForVLC#17]
I can run the TraktForVLC.py file but when I do I get this in a python window

C:\Users\George\Desktop\TraktForVLC-master\requests\packages\urllib3\util\ssl_.p
y:79: InsecurePlatformWarning: A true SSLContext object is not available. This p
revents urllib3 from configuring SSL appropriately and may cause certain SSL con
nections to fail. For more information, see https://urllib3.readthedocs.org/en/l
atest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Python27\lib\site-packages\setuptools-16.0-py2.7.egg\pkg_resources\__init__.p
y:197: RuntimeWarning: You have iterated over the result of pkg_resources.parse_
version. This is a legacy behavior which is inconsistent with the new version cl
ass introduced in setuptools 8.0. In most cases, conversion to a tuple is unnece
ssary. For comparison of versions, sort the Version instances directly. If you h
ave another use case requiring the tuple, please file a bug with the setuptools
project describing that need.

**Comment by XaF** [comment]
It is planned to be corrected in future commits, they are "ready" but not ready to push yet. It should be done by the end of June at worst.
These warnings have been mentionned in issues #11, #12 and #13. They are not of any concern but some changes in ```TraktForVLC``` allows to clear any concern ;)

Keep that issue opened, I'll reference it in the commit message when pushing the changes!

**Comment by XaF** [comment]
Oh, can you tell me your full Python version?

**Comment by grepole121** [comment]
2.7.8

**Comment by XaF** [comment]
Ok, you should be able to make the SSL warning disappear by either upgrading to Python 2.7.9 or installing the python packages ```pyopenssl```, ```ndg-httpsclient``` and ```pyasn1```. Python 2.7.9 seem to have been correcting this behavior.

The first solution is what I would recommend. However, if it's too much trouble for you, you can install the packages using ```pip``` (if you have ```pip```: ```pip install pyopenssl ndg-httpsclient pyasn1```) or using the ```easy_install``` script you should find with your Python installation (```easy_install pyopenssl ndg-httpsclient pyasn1``` I think).

Can you try that and report?

**Comment by grepole121** [comment]
Yes the SSL warning is gone but not the other one.

**Comment by XaF** [comment]
The other one needs an edit that'll push when I have time to clean it, as I said before!
It's not as important, as it is not a security problem or concern. Setuptools changed the way ```pkg_resources``` works and kept working the previous behavior but with a warning. ```TraktForVLC``` should not have any problem running, and the update correcting that will be pushed long before they remove the functionality showing that warning.
