### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IAmFrench** [XaF/TraktForVLC#19]
Hi !
>python version = 3.4

# Installation
## Automatic config
I am trying to install Trakt for vlc but when I start the ```set_registry_keys.bat``` file. But I got an error :

![image](https://cloud.githubusercontent.com/assets/10818450/8025301/58583ad4-0d51-11e5-9ff6-7bd30c6efcab.png)

There is the content of ```config.bat```

![image](https://cloud.githubusercontent.com/assets/10818450/8025324/2c700216-0d52-11e5-88d0-e686912efcff.png)

Folders ```config``` and ```data``` are created.

![image](https://cloud.githubusercontent.com/assets/10818450/8025365/311859ec-0d54-11e5-924b-e70ede986f7a.png)
## VLC config
I follow the instruction [here](https://github.com/XaF/TraktForVLC#configuring-vlc)

# Config 
I edited the ```config.ini``` file whith the pin code

# Launch a show
When I start a show I got this in the console :
![image](https://cloud.githubusercontent.com/assets/10818450/8025412/78162124-0d56-11e5-9c88-68a328dee6d6.png)
 but I can open in a web broser the url, and get an xml file as answer
> http://services.tvrage.com/feeds/search.php?show=The%20Messengers%202015

edit : whith an other file :
![image](https://cloud.githubusercontent.com/assets/10818450/8045248/51ce0572-0e32-11e5-99b5-1689527db3e2.png)

**Comment by XaF** [comment]
For the `set_registry_keys.bat` error, it has been answered in report #15. It is a problem with the directory name containing parenthesis (the `(x86)` part). You can try to escape these parenthesis, or simply move VLC to some other path!

For your second problem, see #2 : it is a VLC error and not a `TraktForVLC` one, and should not prevent `TraktForVLC` (nor VLC) from working.

Please search in the previous issues if your problems haven't been discussed already!
