### ISSUE TITLE
Access error

### ISSUE THREAD

**Issue by hugolapointe** [XaF/TraktForVLC#2]
Hi guys!

Thanks for your app. Can you help me with this issue?

![image](https://cloud.githubusercontent.com/assets/3542305/6312822/35f8d254-b956-11e4-87ce-a6a28b891262.png)

**Comment by XaF** [comment]
The error you have is not at all linked to TraktForVLC but directly to VLC.
VLC is connecting to TVRage to get extra metadata for the video you're watching as per the `tvrage.lua` plugin, thus that access try to TVRage.
Any problem linked to TraktForVLC would not appear in VLC but directly in TraktForVLC!
