### ISSUE TITLE
Won't scrobble

### ISSUE THREAD

**Issue by thekalby** [XaF/TraktForVLC#22]
Running OS X here and followed all the instructions. I'm assuming there's no GUI here or anything to tell me if the extension ran, so I ran "python TraktForVLC.py --debug --small-timers" to see what was going on. It seems that for some reason the extension wont scrobble anything I play. I set the percentage to 3% so it scrobbles my videos, yet it still says "This video is scrobbled : False"  http://pastebin.co/qqXEC7Ae\

Two places this could be comming from
1. There was an error in the beginning that says "A true SSLContext object is not available" Also at other times I've received at 401 error.
2. For the pin on my account, I entered it as "PIN = 88962e01", I assume there arent supposed to be brackets here, but if there were that could be the problem.

Any advice?

**Comment by XaF** [comment]
1. Has been addressed in issue #17 
2. No, that's fine

It seems, from what you tell me, that everything is working fine. Currently, it is not possible for TraktForVLC to Scrobble a video under 80%. It is also not possible to scrobble that video if you didn't spend at least a third of the time watching. The 80% is directly set by Trakt, and the second option is one currently enforced (I plan to set it as a configurable option in the future, as well as making a special trick to allow scrobbling before 80% also).

Have you tried watching a video for a longer time?
