### ISSUE TITLE
Cannot resolve services.tvrage.com

### ISSUE THREAD

**Issue by spac3** [XaF/TraktForVLC#26]
Hi @XaF,

I hope your weekend will either be fun or chilled, whichever you prefer more :)

Thanks for this app/script, this will be an awesome addition for me once I get it working.
I've tried to install your script on VLC for the 1st time tonight and seem to be having similar problems as other users, however I'm not sure if I've missed something during the setup.

This is what I'm running:
VLC 2.2.1 "Weatherwax"
TraktForVLC (Latest commit 9ad799c  on Sep 20)
Python 3.4.3
Microsoft Windows [Version 6.3.9600] aka "Windows 8.1 Pro"

I've updated VLC as advised, but didn't disable the CLI output.

Config (config.ini)
http://pastebin.com/XFudrt0F

More config (config.bat):
http://pastebin.com/t6dCKVbd

The problem:
Then I run VLC 1st and then load in a file, it opens the CLI with it which is fine for now.
However when I load in a file then I get the following output, I believe this is why I don't see updates on Trakt.

CLI Output:
http://pastebin.com/qTGs8AjG

I was then looking around on other tickets and found that if I run the following I get the same as "ciakki" in #23.
http://pastebin.com/mKsWEZGJ

I've also run the import command you suggested to "AquaGen" in #12 
http://pastebin.com/WPaUSqFk

I have however noticed that I do not have any log folders/files, not sure why.

Your thoughts?

**Comment by XaF** [comment]
Hello @spac3,

Ok, so first of all the services.tvrage.com issue is not a `TraktForVLC` but a `VLC` one. It is actually due to the fact that you must have activated the tvrage plugin to get video meta directly from tvrage. If you want those warning to disappear, you should disable that plugin.

It seems however that @ciakki and you are having a similar problem, most probably due to the python version you're using. Before pushing the fix, could you try and replace the files `tvdb_api/__init__.py` and `tvdb_api/tvdb_ui.py` by the ones [available here](https://www.justbeamit.com/iti5g) and tell me if you're able to run `TraktForVLC` following that ?

**Comment by spac3** [comment]
Done, but now I'm getting other stuff:
http://pastebin.com/Fmbwdj60

Should you be online now, please join me in this anonymous chat, it'll make things go quicker. 
https://otr.to/#abpoq

**Comment by XaF** [comment]
Is VLC started?
As said in the log file you posted:
```
Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
```

It seems everything else is fine.

**Comment by spac3** [comment]
Seems like it wants to work:
http://pastebin.com/FvVifWNV

What I'm noticing is that it has a  401 Unauthorized, this made me think of the PIN.
The PIN has not yet been replaced by the API keys.

**Comment by XaF** [comment]
Seems like your PIN didn't authorize you access. Can you [generate a new PIN](https://trakt.tv/pin/2498) and put it in the config file?

**Comment by spac3** [comment]
Did that again:
http://pastebin.com/rUVNCSwe

**Comment by XaF** [comment]
Ok, we're in the right direction.

File `TraktForVLC.py`, line 359, can you replace `'wb'` by '`w`' and tell me if it works?

**Comment by spac3** [comment]
Update, now it's broken :P

http://pastebin.com/NwpcxYAM

**Comment by XaF** [comment]
Ok, it probably broke your `config.yml` file when trying to write it. Could you reset your `config.yml` file, get a new PIN (as I assume the credentials acquired were lost during this step... sorry!) and try to run it again with that last change? As it is touching the writing of the config file, I think you'll have to do these steps until we figure out how to correct what's broken!

**Comment by spac3** [comment]
Perfect, it's updated on trakt.tv.
I think you've found your next update to push :)

Thanks.

**Comment by XaF** [comment]
Good. I'll push that in the next few minutes. Thanks for your bug report!

**Comment by spac3** [comment]
Thanks for your assitinse.
I'll add this in conversation next to Sickbeard and SabNZBd :)
