### ISSUE TITLE
Windows - Process doesn't start

### ISSUE THREAD

**Issue by sidc9** [XaF/TraktForVLC#27]
Hi, I have been trying to configure this for a few days now. 

After running ```start_process.bat``` , nothing happens. There is no .pid file , no error message, no running processes, nothing.

Could you please help me debug this? 

I'm on a Win8.1, with Python 3.4. 

Edit: Found the problem with registry editing dealt with in the Closed Issues section. My solution below is probably wrong and should be ignored.

<s>Also, I had a problem with the ```set_registry_keys.bat```. At first I got errors regarding the syntax to edit registry. I found a minor bug there and finally got the ```set_registry_keys.bat``` to work. I've mentioned the change below in case someone else comes across the same problem.

<s>```REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL```</s>

<s>needs to be modified to </s>

<s>```REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "%vlc_path% %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL```</s>

(Note the  change at %vlc_path%. This needs to be done for all 3 lines with REG ADD command )</s>

Also, the .bat file needs to be run as system administrator or else it will fail with Error: Access Denied.

**Comment by sidc9** [comment]
After some more hunting and debugging, I think I have narrowed down the problem. The TraktForVLC.py seems to complain that it cannot find .pid file. I hope you have some ideas for this problem!

**Comment by XaF** [comment]
Can you try running TraktForVLC in command line?
```
C:\[...]\pythonw.exe
C:\[...]\TraktForVLC\TraktForVLC.py --datadir C:\[...]\TraktForVLC\ --config C:\[...]\TraktForVLC\ --pidfile C:\[...]\TraktForVLC\TraktForVLC.pid --debug --small-timers
```

After editing `[...]` to fit the right paths, obviously.

**Comment by JimiC** [comment]
Here is the error message I receive
```
Traceback (most recent call last):
  File "H:\Downloads\TraktForVLC\TraktForVLC.py", line 870, in <module>
    file(pidfile, "w").write("%s\n" % str(os.getpid()))
NameError: name 'file' is not defined
```

**Comment by XaF** [comment]
Hmhm, seems to be a Python 3 problem I didn't catch before!
Can you try replacing the `TraktForVLC.py` file by the following and report? http://pastebin.com/Fcrf6rbz

**Comment by JimiC** [comment]
Now I get
```
Traceback (most recent call last):
  File "C:\Program Files\Python34\lib\logging\__init__.py", line 980, in emit
    stream.write(msg)
  File "C:\Program Files\Python34\lib\encodings\cp1253.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xeb' in position 77: character maps to <undefined>
Call stack:
  File "H:\Downloads\TraktForVLC\TraktForVLC.py", line 879, in <module>
    daemon=(should_daemon or pidfile))
  File "H:\Downloads\TraktForVLC\TraktForVLC.py", line 205, in __init__
    "Rapha\xebl Beamonte <raphael.beamonte@gmail.com>")
Message: '## Copyright (C) 2014-2015  Rapha\xebl Beamonte <raphael.beamonte@gmail.com>'
Arguments: ()
```

**Comment by XaF** [comment]
Yes, but not only on line 870, I changed multiple references to 'file' by using 'open' instead, as 'open' is both compatible with Python 2 and 3.
Here is another version to try to address your current problem. Not sure what it will give as result, because it seems the problem is linked to the Windows console encoding. Please try this: http://pastebin.com/V2V1HVX6

**Comment by JimiC** [comment]
This version throughs
```
Traceback (most recent call last):
  File "H:\Downloads\TraktForVLC\TraktForVLC.py", line 879, in <module>
    daemon=(should_daemon or pidfile))
  File "H:\Downloads\TraktForVLC\TraktForVLC.py", line 205, in __init__
    u"Rapha\xebl Beamonte <raphael.beamonte@gmail.com>".encode('utf-8'))
TypeError: Can't convert 'bytes' object to str implicitly
```
Let me note here, that with this version and the previous the pid file was getting created.

**Comment by XaF** [comment]
Yep, that's the accent in my name that doesn't pass Windows' console encoding. I don't exactly know why is that, but meh... Windows ;)
Try with this version, that removes the accent in my name: http://pastebin.com/ndxLGGAk

**Comment by JimiC** [comment]
Houston we have lift-off \o/

**Comment by JimiC** [comment]
Turns out the Windows console only supports ANSI characters.
Info: http://stackoverflow.com/questions/30539882/whats-the-deal-with-python-3-4-unicode-different-languages-and-windows

Though some say that there is a workaround with `win-unicode-console`

**Comment by XaF** [comment]
Yeah, that's kind of what I understood. When I'll have some time, I'll think about a workaround to print "ë" or "e" depending on the OS, that way it'll still work while keeping my name intact most of the time ^^

**Comment by JimiC** [comment]
Just want to report that I finally have it working, watching video in VLC, scrobbles in Trakt.tv.  \o/

**Comment by JimiC** [comment]
Just FYI. Running on Python 3.5 (64bit) and looks :+1:

**Comment by XaF** [comment]
Thanks for the information! I should extend the unit tests when I'll have some time to be able to validate an actual use of TraktForVLC using the CI tools!
