### ISSUE TITLE
Cannot access file info in Windows

### ISSUE THREAD

**Issue by gavesc7** [XaF/TraktForVLC#29]
The process starts and seems to work, I have left enabled the DOS command box in VLC to make sure about this, however the displayed information lets me know, that the file is not accessible for the scrobbler.
Furthermore, somehow the pin code is still there, no access token is generated, I'm not sure if I am doing something wrong. The only thing I can think about is that I have all my video files on an external hard drive which is encrypted with BitLocker, may this be the issue? I would appreciate any help.

I am currently using Windows 10 together with VLC 64 bit and Python 3.5.

Anyhow thanks for sharing your work!

**Comment by XaF** [comment]
Hm, I actually never tried working with that on an encrypted drive. Could you paste your `TraktForVLC` debug log file ?

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
