### ISSUE TITLE
TV Shows and Movies not being marked as watched.

### ISSUE THREAD

**Issue by TweCha** [XaF/TraktForVLC#3]
It shows progress on the Trakt.tv website as i'm watching but does not auto mark as being watched.

Also getting errors in the logs:
```
2015-03-10 13:56:43,357::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\TraktForVlc\TraktForVLC.py", line 208, in run
    self.main()
  File "C:\TraktForVlc\TraktForVLC.py", line 236, in main
    vlcStatus = vlc.is_playing()
  File "C:\TraktForVlc\vlcrc\__init__.py", line 92, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\TraktForVlc\vlcrc\__init__.py", line 55, in _command
    raise VLCBadReturn(cmd_ret)
VLCBadReturn 

```
Looped over and over...

**Comment by XaF** [comment]
Could you please raise the loglevel by starting ```TraktForVLC``` in debug mode ? You can do so using the following command:

```bash
python TraktForVLC.py --debug --small-timers
```

You will then find a log file named ```TraktForVLC-DEBUG.log``` that should be in the ```logs``` directory near ```TraktForVLC.py``` (except if you have specified another data directory using the --datadir option). That file will contain more detailed information on the origin of your problem, thus allowing me to understand what happens.

**Comment by TweCha** [comment]
Here: http://pastebin.com/5RqhbXA4
I let the whole episode play.
But for some reason it shows up on Trakt now?

**Comment by XaF** [comment]
Ok, this log shows that all was working perfectly during that video. The error you reported in your first message means that there were some unexpected answer from VLC when TraktForVLC tried to get the information if something was playing or not. Did it happen often or only once?

If it is likely to happen often, you could change your automatic starting of ```TraktForVLC``` to always be in debug mode for a short period of time (without the small-timers, as shown below) so next time you have the problem you could give me the debug information to understand what was the VLC answer to TraktForVLC request.

```bash
python TraktForVLC.py --debug
```

**Comment by TweCha** [comment]
I only started using Trakt since a few days ago and TraktForVLC never worked until i first enabled debug mode. But it seems its working perfectly fine now even in normal mode, i will keep debug mode on and report back here if i run into that problem again.

**Comment by XaF** [comment]
Did you perhaps change anything on the VLC side?
I'm glad it's working for you now, even if in a way, that would be helpful if you stumble upon that problem again as we don't know yet what was the problem!

Also, I just realized but, did you have anything before the ```2015-03-10 13:56:43,357::TraktForVLC::ERROR::An unknown error occurred``` messages in your first log file? Mostly lines starting by "Sent:", "Expected:" and "Got:"? These messages should appear at the default log level.

**Comment by TweCha** [comment]
No i didn't change anything in VLC. The only thing i remember doing different is deleting the ``config.ini`` i had and copied ``config.ini.default`` to start fresh.

And sorry, i deleted all the logs to make sure i didn't get confused between them :(

**Comment by XaF** [comment]
No worries. If you have the problem again, do not hesitate to report it with the debug log if possible!
In the meantime, enjoy using ```TraktForVLC```!
