### ISSUE TITLE
Unable to start episode: 404 Not Found

### ISSUE THREAD

**Issue by klackerz** [XaF/TraktForVLC#30]
Trakt for vlc is unable to mark an episode as watching even after finding it on trakt. It mainly happens for some episodes of anime especially from the new seasons.

Here's the [debug log](http://pastebin.com/f3jD8503)

**Comment by JimiC** [comment]
Probably Trakt.tv was down at that moment.

**Comment by XaF** [comment]
Yup. Seems it was a problem with Trakt. Offline support for `TraktForVLC` should appear at some point, I just don't have that much time to work on that right now, but will do for sure!

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
