### ISSUE TITLE
Movie name matching pattern failing to output correct movie name

### ISSUE THREAD

**Issue by JimiC** [XaF/TraktForVLC#31]
I decided to watch "The Man from U.N.C.L.E." and while checking with Trakt that the movie is scrobbling correctly, I noticed that nothing was happening.
So I decided to look into it and discovered that the `filenameparser/cleanRegexedName` was stripping the last dot in the name causing the lookup for the movie name in 'omdbapi' to fail.

So the solution in this case is to remove the dot (.) from the char array in line 294 ```name = name.strip("-. ")```.

Now, you may say that this may break other cases of movie name matching, and I will agree with you on that, but it can be added as another test case in `test_filenameparser` to assure that nothing that is currently tested, breaks.

P.S.: For testing purposes the filename is "The.Man.from.U.N.C.L.E..2015.1080p.BluRay.x264.DTS-JYK.mkv"

**Comment by XaF** [comment]
That's a good filename to test. I remember that I had some problems with dots like that, I'll check that and see if I can do something besides just removing that dot!

**Comment by JimiC** [comment]
Resolved with bf172a81f7c60f93600ce179c857d48b73877413
