### ISSUE TITLE
Bar on Trakt.tv does not pause if VLC is paused

### ISSUE THREAD

**Issue by ghost** [XaF/TraktForVLC#33]
If I'm playing a movie or TV show and I pause it in VLC, the bar at the top of the page of trakt.tv continues to count minute by minute. Is there a way to fix this?

**Comment by keems26** [comment]
It also doesn't mark the movie as watched, despite the bar reaching the percentage specified in the config file. And I have both settings switched to yes. Does anybody know what could be causing this?

**Comment by XaF** [comment]
Well, it is a way not to spam the Trakt API. When the movie doesn't move on your side, there is no requests sent to Trakt website. I don't know if I'll keep the behavior that way though. I'll think about different options for that.

**Comment by XaF** [comment]
Solved by TraktForVLC 2.x - #88
