### ISSUE TITLE
Daemon Mode not correct for MacOS in docs or example org.TraktForVLC.plist file

### ISSUE THREAD

**Issue by CoderFromCali** [XaF/TraktForVLC#34]
The example given to run in Daemon mode on MacOS is not correct for the .org.TraktForVLC.plist. As it stands the script won't run in daemon mode and won't create log files. To correct this problem change:

``` xml
        <string>[EDIT: /usr/bin/python]</string>
        <string>[EDIT: /path/to/TraktForVLC/TraktForVLC.py]</string>
```

to 

``` xml
        <string>[EDIT: /usr/bin/python]</string>
        <string>[EDIT: /path/to/TraktForVLC/TraktForVLC.py]</string>
        <string>--daemon</string>
```

This will result in 0 length log files being created unless a Warning or above level error message is posted. I like a bit more detail so I prefer this:

``` xml
        <string>[EDIT: /usr/bin/python]</string>
        <string>[EDIT: /path/to/TraktForVLC/TraktForVLC.py]</string>
        <string>--daemon</string>
        <string>--loglevel</string>
        <string>INFO</string>
```

For debug mode/logging use:

``` xml
        <string>[EDIT: /usr/bin/python]</string>
        <string>[EDIT: /path/to/TraktForVLC/TraktForVLC.py]</string>
        <string>--daemon</string>
        <string>--debug</string>
```

**Comment by XaF** [comment]
I actually don't have a Mac, so I mostly trusted users that told me it was the good direction to take! But it's true that Mac should support the daemon mode. I'll edit that in the files.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
