### ISSUE TITLE
Can't start TraktForVLC daemon

### ISSUE THREAD

**Issue by noyseannoys** [XaF/TraktForVLC#35]
Hi,
here's my situation: I have TraktForVLC in  /usr/share/traktforlvc, I set up everything on VLC (as explained https://github.com/XaF/TraktForVLC), configured the config.ini file withe my PIN and then added the line /usr/share/traktvforvlc/TraktForVLC.py --daemon in my .bash_profile.
As I started watching a movie on VLC I saw nothing happened on my TrakTV profile (movie progress and lists..).
So I checked out if the daemon was active, and it's not. Then launched the .py directly even with debug mode and got this:

Traceback (most recent call last):
  File "./TraktForVLC.py", line 880, in <module>
    daemon=(should_daemon or pidfile))
  File "./TraktForVLC.py", line 229, in __init__
    self.__load_config()
  File "./TraktForVLC.py", line 319, in __load_config
    self.TIMER_INTERVAL = self.config.getint("TraktForVLC", "Timer")
  File "/usr/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '60 # Time (sec) between each loop and look of TraktForVLC'

It seems the most important cause is the parsing of the Timer variable. I'm pretty sure it's ok as explained in my config.ini

[VLC]
IP = localhost
Port = 4222

[Trakt]
PIN = [personal_pin_code]

[TraktForVLC]
Timer = 60 # Time (sec) between each loop and look of TraktForVLC
StartWatching = 30 # Time (sec) before considering a video is currently watched
UseFilenames = No # Whether or not to use filenames instead of VLC window title
ScrobblePercent = 90 # Percentage (%) of the video to be spent before scrobbling it
ScrobbleMovie = Yes # Whether or not TraktForVLC will automatically scrobble movies
ScrobbleTV = Yes # Whether or not TraktForVLC will automatically scrobble tv shows
WatchingMovie = Yes # Whether or not movies will be marked as being watched
WatchingTV = Yes # Whether or not tv shows will be marked as being watched

Any ideas ?
Thanks.

**Comment by CoderFromCali** [comment]
The script is not honoring the comments in your config.ini file. It thinks that these are part of the parameters. Remove "# Time (sec) between each loop and look of TraktForVLC" from your config file. Remove all of the other comments, including the # sign as well.

**Comment by noyseannoys** [comment]
Thanks @CoderFromCali ! I was just too stoopid to notice that comments should work with the ";" sign. Now the daemon started. Still can't scrobble from VLC :-( but this issue is solved!
