### ISSUE TITLE
PID functilaity doesn't work well on OS X

### ISSUE THREAD

**Issue by CoderFromCali** [XaF/TraktForVLC#36]
I setup the TrackForVLC script on OS X with the `~/Library/LaunchAgents/org.TraktForVLC.plist` file. In this file I specified:

``` xml
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python</string>
        <string>/Users/myuser/Applications/TraktForVLC/TraktForVLC.py</string>
        <string>--daemon</string>
        <string>--pidfile</string>
        <string>/Users/myuser/Applications/TraktForVLC/TraktForVLC.pid</string>
    </array>
```

Using the command: 

``` shell
    launchctl load ~/Library/LaunchAgents/org.TraktForVLC.plist
```

TrakForVLC runs as expected. It creates the file `/Users/myuser/Applications/TraktForVLC/TraktForVLC.pid` as expected and the file contains the running PID. However, if i kill the python proccess that is running the script with a normal kill the file `/Users/myuser/Applications/TraktForVLC/TraktForVLC.pid` is not removed. If I then launch the script again either from launchctl or from the command line TrakForVLC exits saying that another instance is running. This is the expected behavior if running the process again, however, the `/Users/myuser/Applications/TraktForVLC/TraktForVLC.pid` file should have been deleted when the script was killed normally. The request is for the `/Users/myuser/Applications/TraktForVLC/TraktForVLC.pid` file to be cleaned up when TraktForVLC is stopped normally.

Also the error message should indicate that there is an existing PID file and where it is. It should also state that the user should check to see if TrakForVLC is running else where. If it is not remove the PID file and try again.

**Comment by XaF** [comment]
That's a good point, I'll add the SIGTERM signal to managed signals!

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
