### ISSUE TITLE
Cannot save the settings

### ISSUE THREAD

**Issue by achmetinternet** [XaF/TraktForVLC#38]
I am on Win10 and use the 32bit version of VLC 2.2.2

Whenever I enter settings in the Interface section of the settings and want to save them, they disappear next time I open the settings.

Edit:
I installed 2.2.0 and tried to leave the "oldrc" value in the field where it appears and it remains there after saving but the "localhost:4222" value does not remain after saving.

**Comment by XaF** [comment]
In some versions of VLC, the settings are saved but does not appear in the settings window. You just need to be careful not to erase your settings by opening that window again and saving... I don't know why it's like that, but that's mostly a VLC problem, not a `TraktForVLC` one, so I can't do anything for that ;(

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
