### ISSUE TITLE
pythonw.exe?

### ISSUE THREAD

**Issue by baronebarra** [XaF/TraktForVLC#4]
I followed all the steps in your guide, but the script doesen't work. Surely the solution is easy and I'm just a n00b, but when I try to open start_process.bat a window pop ups from the cmd and says

Windows cannot find "pythonw". Make sure you typed the name correctly, and then try again.

Do you have a solution? I've downloaded python27 (didn't have it on my PC before) and tried to set the path but it didn't fix the issue, or I'm doing something wrong
Thanks!

**Comment by XaF** [comment]
Did you edit the ```start_process.bat``` file to set the different informations needed ?

The content of the file must be edited to reflect your computer's paths:
```batch
start "TraktForVLC" [full/path/to/python(w).exe] [full/path/to/TraktForVLC.py] --datadir [full/path/to/directory/TraktForVLC] --config [full/path/to/directory/TraktForVLC]
```

You should paste here the content of that file if it still doesn't work when you've edited your file!

**Comment by baronebarra** [comment]
Thanks for the reply.
I hadn't changed the path to pythonw.exe, now it seems to work: if I open start-process.bat it doesen't give me any error. But then I play a file in VLC but I can't see it in my Trakt history.
Of course I configured VLC properly and I tried with different episodes, but with no luck.

**Comment by XaF** [comment]
Did you let it enough time while wathing the episode ? There is a one minute delay between each time ```TraktForVLC``` look at what is happening in ```VLC```.

Also, you could add at the end of the line starting by ```start``` in the ```start_process.bat``` file the options ```--debug``` and ```--small-timers```. The ```--debug``` option will create a ```TraktForVLC-DEBUG.log``` file containing more detailed information about what is happening in ```TraktForVLC```, while the ```--small-timers``` option will reduce the time between checks to only 5 seconds. If there's something wrong in ```TraktForVLC```'s work, we will see that in that log file.

**Comment by baronebarra** [comment]
The log file says:

"2015-03-12 19:44:07,703::TraktForVLC::ERROR::Config file C:\Users\Emmo\Desktop\Trakt4VLC/config.ini not found, exiting."

That "/" before the name of the file looks wrong, but the start_process.bat seems fine.

**Comment by XaF** [comment]
Ok, can you change the following line by the end of ```TraktForVLC.py``` from:
```python
    configfile = config + "/config.ini"
```
to
```python
    configfile = os.path.join(config, "config.ini")
```
and report back?

**Comment by baronebarra** [comment]
tried that, same result, config.ini non found...

**Comment by XaF** [comment]
Just to be sure, did you copy (and edit) the ```config.ini.default``` file to ```config.ini``` and put it in your ```C:\Users\Emmo\Desktop\Trakt4VLC``` directory ?

Would you create a ```test.py``` file with the following source and run it with python to see what happens? It's difficult for me to test directly as I don't have any proper Windows installation available.

```python
import os.path

configdir = r"C:\Users\Emmo\Desktop\Trakt4VLC"
configfile = os.path.join(configdir, "config.ini")

if os.path.exists(configdir):
    print configdir, "exists"
else:
    print configdir, "does not exists"

if os.path.exists(configfile):
    print configfile, "exists"
else:
    print configfile, "does not exists"

if os.path.isfile(configfile):
    print configfile, "is file"
else:
    print configfile, "is not file"
```

**Comment by baronebarra** [comment]
Oh, that's the step I was missing. I didn't create the new config.ini file, I just edited and kept the old config.ini.default... 
Now it's working properly!
Thank you very much for the support :)
