### ISSUE TITLE
Process does not start

### ISSUE THREAD

**Issue by vanquirius** [XaF/TraktForVLC#49]
Hello there!

Thank you very much for taking the time to write this software.
I had this working before flawlessly, but I have run into some trouble in a fresh install of Windows 10.

I have installed Python-3.5.0 for Windows, configured both config.bat and start_process.bat and added the proper keys to the Windows registry.

When I run TraktForVLC, no Python process shows up. I have tried launching straight from the command line, activated --debug tags and nothing seems to be going on,

Any tips?

Regards,
Marcelo

[windows_batch.zip](https://github.com/XaF/TraktForVLC/files/254021/windows_batch.zip)

**Comment by XaF** [comment]
Did you look at the `logs/` directory inside `TrackForVLC`'s path? Is there a `TrackForVLC-DEBUG.log` file? If so, more information should be there!

**Comment by vanquirius** [comment]
No log at all was generated :-(

**Comment by sohalartz** [comment]
I have same problem i get this in python promt 

`Traceback (most recent call last):
  File "C:\Python34\lib\configparser.py", line 1115, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'TraktForVLC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\TraktForVLC.py", line 880, in <module>
    daemon=(should_daemon or pidfile))
  File "..\TraktForVLC.py", line 229, in __init__
    self.__load_config()
  File "..\TraktForVLC.py", line 319, in __load_config
    self.TIMER_INTERVAL = self.config.getint("TraktForVLC", "Timer")
  File "C:\Python34\lib\configparser.py", line 780, in getint
    return self._get(section, int, option, raw=raw, vars=vars)
  File "C:\Python34\lib\configparser.py", line 775, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Python34\lib\configparser.py", line 753, in get
    d = self._unify_values(section, vars)
  File "C:\Python34\lib\configparser.py", line 1118, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'TraktForVLC'`

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
