### ISSUE TITLE
Have option to read movie name from filename instead of Metadata.

### ISSUE THREAD

**Issue by TweCha** [XaF/TraktForVLC#5]
Hello! Me again.
I saw that TraktForVlc wasn't showing a movie i was watching because it was getting the movie name from the metadata instead of from the filename.

Here is a screenshot from Tools>Media Information
![bug](https://cloud.githubusercontent.com/assets/10759579/6671903/8a95cc4a-cc43-11e4-8fc3-48b1d053bbc6.png)

And here is my log:
http://pastebin.com/hGiPmGfa

**Comment by XaF** [comment]
```TraktForVLC``` was using the filename in the early stage, but most of the actions it can do are limited to the information it can get from the remote control interface of ```VLC```.
It seems the version of ```VLC``` I am currently using (2.2.0-rc2) has an easy and reliable way of getting the filename. I will add that behavior, and set it as an option in the configuration so users will be able to choose to use ```VLC```'s window title or the open file path.
