### ISSUE TITLE
Config.bat not accepting paths with spaces in it

### ISSUE THREAD

**Issue by Hillgrove** [XaF/TraktForVLC#51]
I can't set up the config.bat file proberly as the path to my VLC is:

```
 C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
```

I've tried double quotes and 2 x double quotes and single quotes.. nothing works. At best the command prompt output is this:

---
## \-     Add config to all your vlc files for TraktForVLC   -

VLC configuration : localhost:4222
Editing your registry keys for formats "avi, mkv, mov, mp4, wmv, ts, mpg"
\VideoLAN\VLC\vlc.exe'\" --extraintf=rc --rc-host=\"localhost\":\"4222\" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" was unexpected at this time.

Secondly... the options for Python in the config.bat.. don't I have to touch those?!? Nothing is mentioned on the install guide.

**Comment by Hillgrove** [comment]
bump... 3 months and no words from the developers?!?

**Comment by XaF** [comment]
Kind of busy on other projects at the moment, and I don't have the windows installation needed to help you properly. Can you please try with #56 submitted by @AndreaPro ? I need people to confirm his patch works properly on different windows installations to merge it, and it could at the same time fix your problem.

**Comment by Hillgrove** [comment]
Thanks for the reply - I'll check it out :)

**Comment by Lels59** [comment]
@Hillgrove Have you solved your issue ? I have the same exact problem and I tried several things but nothing did it...

**Comment by Hillgrove** [comment]
No, I didn't get it to work.. I switched to Simkl instead that has a VLC plugin that works.

**Comment by AndreaPro** [comment]
I can try to help you, I've tried my commit on 4 different windows machines
and two OS X and it works.

Il ven 28 ott 2016, 20:25 Hillgrove <notifications@github.com> ha scritto:

**Comment by Lels59** [comment]
@AndreaPro 
Did you write something special in your .bat files ?

**Comment by AndreaPro** [comment]
I've changed some lines because they were causing some errors and the files
weren't working for me without the fix.

Il dom 30 ott 2016, 12:17 Lels59 <notifications@github.com> ha scritto:

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
