### ISSUE TITLE
Progress bar shows, but not scrobbles

### ISSUE THREAD

**Issue by Dimsok** [XaF/TraktForVLC#57]
I use windows, and i have red progress bar on trakt.tv site, but never makes it scrobble. I even change ScrobblePercent = 5 10 etc to get it works, but nothing. And with deafault 90 i rewind video on the end and nothing. In log i always have "This video is scrobbled : False". And i don't know how, but i get one video scrobbled. Don't have any guess for which reason.

**Comment by Pegoth** [comment]
Happens to me too, here is the log of fully watched TV show (debug, 5MB):
[TraktForVLC-DEBUG.txt](https://github.com/XaF/TraktForVLC/files/740277/TraktForVLC-DEBUG.txt)

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
