### ISSUE TITLE
Need some help getting Trakt for VLC working

### ISSUE THREAD

**Issue by FlickCM** [XaF/TraktForVLC#60]
First, some spec:

Mac OS X 10.12.2
VLC v 2.2.4

I previously had trakt for vlc working, scrobbling and everything but after some clean reinstalls etc it no longer does. I uninstalled vlc completely, reinstalled trakt and still nothing. Today I decided to revisit and see if I can get it working again. I followed your debug guide, have it set to localhost: 4222 using lua instead of rc as VLC was refusing to save my settings. Someone in the comments to your trouble shooting mentioned that worked. 

I'm currently watching Sherlock S04E02 from a p2p site, with the debug console going. It seems to be sending and receiving information but traktforVLC keeps coming back saying that No tv show, nor movie found. Which I find hard to believe. Initially it was saying that I was unauthorised and getting a 401 error. I noticed in the trakt.py file that my pin was not in the document, so I popped it in and I stopped receiving that error. 

Wondering if you have any further instruction on how I could rectify this.

**Comment by XaF** [comment]
First of all, I have to mention that the TraktForVLC project do not approve of using illegal P2P and nor do I. So I hope you had your Sherlock episode legally downloaded :) 

Second of all, I cannot help you without the log files. So please provide them! :) 

Finally, as it is mentioned at multiple locations here, the "rc" module disappears from the settings once you reopen them, but should be active after you saved the settings the first time as long as you do not change them after that.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
