### ISSUE TITLE
Error at starting TraktForVLC.py script

### ISSUE THREAD

**Issue by dyxen** [XaF/TraktForVLC#62]
Hi

OS: Elementary OS (Debian)
VLC Version: 2.2.2

When i try to start the script i get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/vlc/TraktForVLC-master/TraktForVLC.py", line 38, in <module>
    from pkg_resources import parse_version
ImportError: No module named pkg_resources
```

Image: [Imgur](http://imgur.com/a/5NTPR)

I copied your script in: `/usr/lib/vlc/`

**Comment by Lihis** [comment]
Could it be that you're missing `python-pkg-resources` package?

**Comment by dyxen** [comment]
Yep that was a problem. Thanks.

Now when I tick "Remote control interface" in Main interfaces i got that oldrc in bottom text box. And when i delete old and only keep rc then save. Next time When i open settings the "Remote control interface" is unticked and text box is empty.

**Comment by Lihis** [comment]
I have had same behavior but it has not been a problem at least for me. As in `README.md` states:
`TraktForVLC can use oldrc, but the behavior of rc is much more predictable thus preferable.`

**Comment by XaF** [comment]
I don't really know why but yeah, when putting "rc" in the settings it doesn't appear in the settings after saving and reopening. Probably because "rc" is not available in the tickable boxes. But it still work usually. And yeah, 'rc' is recommended over 'oldrc'.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
