### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by matthewdias** [XaF/TraktForVLC#7]
Does this work for mac?

**Comment by XaF** [comment]
I don't have a Mac so no way to test it, but as it is not using system specific commands, it should! 

If you can try it and report back, that would be interesting.

**Comment by thibthib** [comment]
I tested it on my 10.10.3 Yosemite mac, with Python 2.7.6, and it works just perfect. I just didn't try to put the script on login, but I don't see why there would be an issue.

**Comment by matthewdias** [comment]
Finally got the time to test it and it works. Now I just need to find a good way to run at login.

**Comment by XaF** [comment]
Thank you @thibthib and @matthewdias for the feedback on Mac!
@matthewdias if you want to propose a step by step way to set TraktForVLC to start at login, I'll gladly include it in the README.

**Comment by thibthib** [comment]
To start at login there is two main ways, the .plist one and the Automator app one. For the .plist method, you have to create a file containing the following text : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>org.user.TraktForVLC</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python</string>
        <string>/path/to/TraktForVLC.py</string>
        <string>--loglevel=INFO</string>
    </array>
    <key>WorkingDirectory</key>
    <string>/path/to/TraktForVLC</string>
    <key>RunAtLoad</key>
    <true />
    <key>LaunchOnlyOnce</key>
    <true />
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
```

Then change the path to your script, and save this file as `org.TraktForVLC.plist` in your `~/Library/LaunchAgents/` folder.

The last step is to load the file at startup, with the command :
`launchctl load ~/Library/LaunchAgents/org.user.TraktForVLC.plist`

And you're good to go !

To check if the script is started (the load command automatically starts it) your can check if it appears in the list when you `launchctl list`

To remove your script from startup loading, you just have to : 
`launchctl unload ~/Library/LaunchAgents/org.user.TraktForVLC.plist`

**Comment by matthewdias** [comment]
If you want a gui in case you do this regularly I recommend Lingon - https://www.peterborgapps.com/lingon/

**Comment by XaF** [comment]
I'll probably include directly that ```.plist``` file in TraktForVLC's files and give the directions in the README. Lots of commits are currently pending, that'll be in my next batch!
Thanks guys :)
