### ISSUE TITLE
Suddenly the scrobble/start is returning 404

### ISSUE THREAD

**Issue by ltburch** [XaF/TraktForVLC#70]
I updated to the latest codebase but the scrobble/start post always returns 404.

I checked the API and it seems the server *may* have changed I tried api.trakt.tv, but it didn't matter it is probably an alias for the old name anyway.

The API docs say oauth is required, is perhaps the certificate no longer valid for the API?  If it was you would figure a 401 not a 404 but sometimes there is no telling what error code it may return.

Anyone else experiencing this, it was working until recently.

**Comment by Dimsok** [comment]
Seems like working for me still. Did you try to request new pin?

**Comment by XaF** [comment]
@Dimsok 's proposition is a good start.
It would be also really helpful if you could provide a DEBUG log of the application!

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
