### ISSUE TITLE
Problem with urllib? "Type str doesn't support the buffer API" Or requests?

### ISSUE THREAD

**Issue by kerstin** [XaF/TraktForVLC#77]
Hi there, I updated TraktForVLC a couple of days ago, hoping to fix some other problem, but ever since I haven't been able to scrobble anything anymore.

I did several clean installs of TraktForVLC (cloned the repo from here) with virtualenvs for different Python versions but I seem to always end up getting the following error:
```
2017-09-29 23:58:39,304::VLCRemote::DEBUG::<- Received: b'19'
2017-09-29 23:58:39,305::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "/PATH_TO_PROG/TraktForVLC/TraktForVLC.py", line 394, in run
    self.main()
  File "/PATH_TO_PROG/TraktForVLC/TraktForVLC.py", line 461, in main
    currentFileName = unquote(currentFileName)
  File "/PATH_TO_VENVS/.pyenv/versions/3.4.2/lib/python3.4/urllib/parse.py", line 519, in unquote
    if '%' not in string:
TypeError: Type str doesn't support the buffer API
```

I'd attach a debug log, but the only log file I get in /logs is `agentlog.log`. The error which is (continuously) logged there is:
```
Traceback (most recent call last):
  File "/PATH_TO_PROG/TraktForVLC/TraktForVLC.py", line 36, in <module>
    import requests
ImportError: No module named requests
```

... Requests is there, though (installed via `requirements.txt`).
```
$ pip freeze
CacheControl==0.12.3
certifi==2017.7.27.1
chardet==3.0.4
fuzzywuzzy==0.15.1
idna==2.6
imdbpie==4.3.0
lockfile==0.12.2
msgpack-python==0.4.8
python-Levenshtein==0.12.0
requests==2.18.4
requests-cache==0.4.13
six==1.11.0
tvdb-api==2.0
urllib3==1.22
wheel==0.30.0
```

My new PIN also doesn't get replaced with an access & refresh token.

I'm currently trying to scrobble from Mac OS X 10.9.5. I might be able to try on a newer Mac OS X version soon though that's only good for testing (all my scrobbling is done from 10.9.5).

**Comment by XaF** [comment]
The build seemed to be passing with Python 3.4, however the tests are unfortunately not running the full application (might want to add that in the future...)

The absence of log file is mostly related to the fact that in the current version, it only generated a log file when running as daemon in order not to create a lot of log files when debugging manually. You could either start it with --daemon or with --pidfile some_file.txt to make it create that log file (the second solution will not run the program as daemon, but will consider it as a daemon).

Also, could you try running it using Python 2.7 ? We should at least be able to eliminate the "buffer API" problem which seem oddly related to Python 3.

**Comment by kerstin** [comment]
Okay, looks like I managed to fix it by adding one line of code. (;

**Comment by kerstin** [comment]
I could submit a PR for the change I made to make it work on my end, though that likely won't fix the overall problem.

The change I made was in an if/else statement, though I'm currently looking at what's "further up" in the code. Do the vlcrc functions return byte strings for a (good) reason?

**Comment by kerstin** [comment]
Will test with 2.7.9 also.

Btw. my fix helped with scrobbling a movie but I can't scrobble a series anymore I could scrobble fine before. :P Argh!

**Comment by kerstin** [comment]
Looks like I managed to fix the TVDB problem as well.  ^^ <- I need this to be able to scrobble my series with either Py2 or Py3.

My Python 3 fix for the bytes error works with Python 2 too, will send 2 PRs for them.

**Comment by kerstin** [comment]
(Btw. replacement of PIN with tokens in the config file worked fine once I fixed the bytes/str error and renewed the PIN.)

**Comment by kerstin** [comment]
Btw. should the README reflect that  `--debug` mode won't produce a debug log anymore? The way it's worded right now it suggests it does.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
