### ISSUE TITLE
set_registry_keys.bat syntax error windows 8.1

### ISSUE THREAD

**Issue by bluishmatt** [XaF/TraktForVLC#8]
The filename, directory name, or volume label syntax is incorrect.
----------------------------------------------------------
-     Add config to all your vlc files for TraktForVLC   -
----------------------------------------------------------
VLC configuration : localhost:4222
Editing your registry keys for formats ""
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
Registry keys modified, thanks for using !
Press any key to continue . . .

**Comment by XaF** [comment]
I don't have windows to try, so I will ask you to test on your side:
In ```set_registry_keys.bat```, can you replace the line:
```batch
call config.bat
```

By the following:
```batch
call %~dp0config.bat
```

And tell me if it works or if you have different errors?

**Comment by bluishmatt** [comment]
call %~dp0config.bat seemed to work.


However, I noticed that:

set_registry_keys.bat    -- >     echo Editing your registry keys for
formats "%vlc_formats%"

calls the vlc_formats variable from the config.bat but theres no
vlc_formats in config.bat, just "formats"

set formats=avi, mkv, mov, mp4, wmv, ts, mpg


I changed that vlc_formats to formats.:
echo Editing your registry keys for formats "%formats%"

now it finds the formats.

----------------------------------------------------------
-     Add config to all your vlc files for TraktForVLC   -
----------------------------------------------------------
VLC configuration : localhost:4222
Editing your registry keys for formats "avi, mkv, mov, mp4, wmv, ts, mpg"
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
Registry keys modified, thanks for using !
Press any key to continue . . .

**Comment by XaF** [comment]
Perfect for the ```call %~dp0config.bat```, thanks for the follow-up!
You're right for the ```formats```/```vlc_formats``` variable, that's effectively a mistake!

I'll push both of those corrections in a commit soon!

**Comment by bluishmatt** [comment]
great! Let me know if you have any idea about that REG ADD error...

**Comment by XaF** [comment]
Could you add a ```echo``` in the FOR lines, so we can see what is the command that is actually tried on the system ?
For instance, the following line:
```batch
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"%vlc_path%" %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL
```

Would become:
```batch
FOR %%G IN (%formats%) DO echo REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"%vlc_path%" %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL
```

You shouldn't have any error, as it won't do anything but print the command so we can understand what ```REG ADD``` is tried and what is perhaps missing!

**Comment by bluishmatt** [comment]
Well that just gave me this:

----------------------------------------------------------
-     Add config to all your vlc files for TraktForVLC   -
----------------------------------------------------------
VLC configuration : localhost:4222
Editing your registry keys for formats "avi, mkv, mov, mp4, wmv, ts, mpg"
Registry keys modified, thanks for using !
Press any key to continue . . .

I don't know if its correct... Didn't seem to do anything?

**Comment by XaF** [comment]
Oh, right, my bad. Can you remove the ```>NUL``` at the end of the line too?

**Comment by bluishmatt** [comment]
C:\TraktForVLC\windows_batch>´╗┐:: TraktForVLC, to link VLC watching to
trakt.tv
 updating
The filename, directory name, or volume label syntax is incorrect.
----------------------------------------------------------
-     Add config to all your vlc files for TraktForVLC   -
----------------------------------------------------------
VLC configuration : localhost:4222
Editing your registry keys for formats "avi, mkv, mov, mp4, wmv, ts, mpg"
REG ADD "HKCR\VLC.avi\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Pro
gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localh
ost":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mkv\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Pro
gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localh
ost":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mov\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Pro
gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localh
ost":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mp4\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Pro
gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localh
ost":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.wmv\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Pro
gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localh
ost":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.ts\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Prog
ram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localho
st":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mpg\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d
"\"C:\Pro
gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localh
ost":"4222" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.avi\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (
x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222"
--rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.mkv\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (
x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222"
--rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.mov\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (
x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222"
--rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.mp4\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (
x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222"
--rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.wmv\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (
x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222"
--rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.ts\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (x
86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222" -
-rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.mpg\shell\Open\command" /ve /t REG_SZ /d "\"C:\Program
Files (
x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"4222"
--rc-quiet --started-from-file \"%1\"" /f
REG ADD "HKCR\VLC.avi\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program
Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":
"4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mkv\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program
Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":
"4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mov\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program
Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":
"4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mp4\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program
Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":
"4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.wmv\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program
Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":
"4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.ts\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program F
iles (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":"
4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
REG ADD "HKCR\VLC.mpg\shell\PlayWithVLC\command" /ve /t REG_SZ /d
"\"C:\Program
Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe" --extraintf=rc
--rc-host="localhost":
"4222" --rc-quiet --started-from-file --no-playlist-enqueue \"%1\"" /f
Registry keys modified, thanks for using !
Press any key to continue . . .

**Comment by bluishmatt** [comment]
For some reason I get this now... (I changed back to before you told me to
add echo and remove the >nul...


C:\TraktForVLC\windows_batch>´╗┐:: TraktForVLC, to link VLC watching to
trakt.tv
 updating
The filename, directory name, or volume label syntax is incorrect.

**Comment by XaF** [comment]
Can you try to run the following command directly in command line (cmd.exe), and as admin as we are touching directly the register ?
```batch
REG ADD "HKCR\VLC.avi\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"C:\Pro gram Files (x86)\VideoLAN\VideoLAN\VLC\vlc.exe\" --extraintf=rc --rc-host=\"localhost\":\"4222\" --rc-quiet --started-from-file --playlist-enqueue \"%1\"" /f
```

That's the first one we got from echo, I just changed the escapes for the quotes!

About your error when reverting, would it be possible that you reverted the ```call config.bat``` ? Because that's the kind of error that comes when you try to call a file, and we're only calling the ```config.bat``` in that script.

**Comment by bluishmatt** [comment]
The operation completed successfully.

No, I didn't modify config.bat

**Comment by XaF** [comment]
Ok, so we'll make the following changes:

###### In ```config.bat```
The following line:
```batch
set vlc_opts=--extraintf=rc --rc-host="%ip%":"%port%" --rc-quiet
```
By:
```batch
set vlc_opts=--extraintf=rc --rc-host=\"%ip%\":\"%port%\" --rc-quiet
```

###### In ```set_registry_keys.bat```
The following three lines:
```batch
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\Open\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file \"%%1\"" /f >NUL
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\PlayWithVLC\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file --no-playlist-enqueue \"%%1\"" /f >NUL
```
By:
```batch
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"%vlc_path%" %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\Open\command" /ve /t REG_SZ /d "\"%vlc_path%" %vlc_opts% --started-from-file \"%%1\"" /f >NUL
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\PlayWithVLC\command" /ve /t REG_SZ /d "\"%vlc_path%" %vlc_opts% --started-from-file --no-playlist-enqueue \"%%1\"" /f >NUL
```

My ```set_registry_keys.bat``` file looks like that currently:
```batch
@echo off

:: Change current directory to the directory where we have out batch file
cd /D %~dp0

:: Load configuration file for the path needed
call ".\config.bat"

echo ----------------------------------------------------------
echo -     Add config to all your vlc files for TraktForVLC   -
echo ----------------------------------------------------------

echo VLC configuration : %ip%:%port%

echo Editing your registry keys for formats "%formats%"

FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\AddToPlaylistVLC\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file --playlist-enqueue \"%%1\"" /f >NUL
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\Open\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file \"%%1\"" /f >NUL
FOR %%G IN (%formats%) DO REG ADD "HKCR\VLC.%%G\shell\PlayWithVLC\command" /ve /t REG_SZ /d "\"%vlc_path%\" %vlc_opts% --started-from-file --no-playlist-enqueue \"%%1\"" /f >NUL

echo Registry keys modified, thanks for using !

pause
```

I changed the ```call %~dp0config.bat``` that I gave you before by just ```call ".\config.bat"``` as I already put a ```cd %~dp0``` before (now improved to ```cd /D %~dp0``` to follow drives if needed).

##### Finally
Can you try to execute the batch script with those changes? Hopefully you won't have your weird output. If you kept the same ```cmd.exe``` open, you could try to close it and use a new one just to be sure that's not tokens of the previous executions!

**Comment by bluishmatt** [comment]
I closed all cmd's and opened it again as administrator:


C:\Windows\system32>´╗┐:: TraktForVLC, to link VLC watching to trakt.tv
updating

The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
----------------------------------------------------------
-     Add config to all your vlc files for TraktForVLC   -
----------------------------------------------------------
VLC configuration : localhost:4222
Editing your registry keys for formats "avi, mkv, mov, mp4, wmv, ts, mpg"
Registry keys modified, thanks for using !
Press any key to continue . . .

**Comment by bluishmatt** [comment]
p.s I copied your set_registry_keys.bat code. (instead of editing mine)

**Comment by XaF** [comment]
I'm puzzled by the ```The filename, directory name, or volume label syntax is incorrect``` lines and the fact that you have the first line of the comments in the file (```:: TraktForVLC, to link VLC watching to trakt.tv updating```) appearing in your command line along with weird chars (```´╗┐```).

Thus, it seems that the registry keys have been edited properly. You can verify by going to ```regedit.exe``` and check the key ```HKCR\VLC.mp4\shell\AddToPlaylistVLC\command``` for instance (```HKCR``` can be named ```HKEY_CLASSES_ROOT```, they're aliases). If the data corresponds to what we asked for (the RC calls msut be in there), then it worked! (even with the errors at first that I don't understand...)

**Comment by bluishmatt** [comment]
Seems like it worked!

However, in my vlc shortcut I have :

"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" vlc --extraintf=rc
--rc-host=localhost:4222

VLC Spits out these errors:

File reading failed:

VLC could not open the file "C:\Program Files (x86)\VideoLAN\VLC\vlc" (No
such file or directory).

Your input can't be opened:

VLC is unable to open the MRL
'file:///C:/Program%20Files%20%28x86%29/VideoLAN/VLC/vlc'. Check the log
for details.


And a CMD style console is open with some earnings, no such file or
directory,... I cant seem to copy the text. Tomorrow i'll type it out..

**Comment by XaF** [comment]
In that shortcut:
```
"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" vlc --extraintf=rc --rc-host=localhost:4222
```
You have a reference to ```vlc``` that shouldn't be here! Can you correct it by the following?
```
"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --extraintf=rc --rc-host=localhost:4222
```
With that reference to ```vlc```, VLC is actually trying to open a file named ```vlc``` to read it.

Was that a shortcut you made yourself, or one that was made using the ```set_registry_keys.bat``` file? That last case would be really weird.

**Comment by bluishmatt** [comment]
nah, I just made a normal shortcut on the desktop and added :

https://github.com/XaF/TraktForVLC#with-command-line

note that the text in the greyish box has 'vlc' too.. I foolishly copied
the whole thing :D

**Comment by XaF** [comment]
Ok! Glad if it works now!
I'm still curious about the ```The filename, directory name, or volume label syntax is incorrect``` errors you had when running the ```set_regedit_keys.bat``` file. Would you be kind to create the following files in the same directory as the batch scripts and run them the same way you did yesterday to see what happen?

##### File ```test1.bat```
```batch
cd %~dp0
```

##### File ```test2.bat```
```batch
cd /D %~dp0
```

##### File ```test3.bat```
```batch
cd "%~dp0"
```

##### File ```test4.bat```
```batch
cd /D "%~dp0"
```

##### File ```test5.bat```
```batch
cd %~dp0
call ".\config.bat"
```

##### File ```test6.bat```
```batch
cd /D %~dp0
call ".\config.bat"
```

##### File ```test7.bat```
```batch
cd "%~dp0"
call ".\config.bat"
```

##### File ```test8.bat```
```batch
cd /D "%~dp0"
call ".\config.bat"
```

**Comment by bluishmatt** [comment]
I put pause to each one.:

1:


C:\TraktForVLC\windows_batch>cd C:\TraktForVLC\windows_batch\

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

2:


C:\TraktForVLC\windows_batch>cd /D C:\TraktForVLC\windows_batch\

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

3.


C:\TraktForVLC\windows_batch>cd "C:\TraktForVLC\windows_batch\"

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .


4.

C:\TraktForVLC\windows_batch>cd /D "C:\TraktForVLC\windows_batch\"

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

5:


C:\TraktForVLC\windows_batch>cd C:\TraktForVLC\windows_batch\

C:\TraktForVLC\windows_batch>call ".\config.bat"

C:\TraktForVLC\windows_batch>set python="C:\Program Files\Python
3.5\pythonw.exe
"

C:\TraktForVLC\windows_batch>set tfv_py=C:\TraktForVLC\TraktForVLC.py

C:\TraktForVLC\windows_batch>set tfv_data=C:\TraktForVLC

C:\TraktForVLC\windows_batch>set tfv_config=C:\TraktForVLC\

C:\TraktForVLC\windows_batch>set tfv_pidfile=C:\TraktForVLC\TraktForVLC.pid

C:\TraktForVLC\windows_batch>set vlc_path=C:\Program Files
(x86)\VideoLAN\VLC\vl
c.exe

C:\TraktForVLC\windows_batch>set ip=localhost

C:\TraktForVLC\windows_batch>set port=4222

C:\TraktForVLC\windows_batch>set formats=avi, mkv, mov, mp4, wmv, ts, mpg

C:\TraktForVLC\windows_batch>set vlc_opts=--extraintf=rc
--rc-host=\"localhost\"
:\"4222\" --rc-quiet

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

6:


C:\TraktForVLC\windows_batch>cd C:\TraktForVLC\windows_batch\

C:\TraktForVLC\windows_batch>call ".\config.bat"

C:\TraktForVLC\windows_batch>set python="C:\Program Files\Python
3.5\pythonw.exe
"

C:\TraktForVLC\windows_batch>set tfv_py=C:\TraktForVLC\TraktForVLC.py

C:\TraktForVLC\windows_batch>set tfv_data=C:\TraktForVLC

C:\TraktForVLC\windows_batch>set tfv_config=C:\TraktForVLC\

C:\TraktForVLC\windows_batch>set tfv_pidfile=C:\TraktForVLC\TraktForVLC.pid

C:\TraktForVLC\windows_batch>set vlc_path=C:\Program Files
(x86)\VideoLAN\VLC\vl
c.exe

C:\TraktForVLC\windows_batch>set ip=localhost

C:\TraktForVLC\windows_batch>set port=4222

C:\TraktForVLC\windows_batch>set formats=avi, mkv, mov, mp4, wmv, ts, mpg

C:\TraktForVLC\windows_batch>set vlc_opts=--extraintf=rc
--rc-host=\"localhost\"
:\"4222\" --rc-quiet

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

7:


C:\TraktForVLC\windows_batch>cd "C:\TraktForVLC\windows_batch\"

C:\TraktForVLC\windows_batch>call ".\config.bat"

C:\TraktForVLC\windows_batch>set python="C:\Program Files\Python
3.5\pythonw.exe
"

C:\TraktForVLC\windows_batch>set tfv_py=C:\TraktForVLC\TraktForVLC.py

C:\TraktForVLC\windows_batch>set tfv_data=C:\TraktForVLC

C:\TraktForVLC\windows_batch>set tfv_config=C:\TraktForVLC\

C:\TraktForVLC\windows_batch>set tfv_pidfile=C:\TraktForVLC\TraktForVLC.pid

C:\TraktForVLC\windows_batch>set vlc_path=C:\Program Files
(x86)\VideoLAN\VLC\vl
c.exe

C:\TraktForVLC\windows_batch>set ip=localhost

C:\TraktForVLC\windows_batch>set port=4222

C:\TraktForVLC\windows_batch>set formats=avi, mkv, mov, mp4, wmv, ts, mpg

C:\TraktForVLC\windows_batch>set vlc_opts=--extraintf=rc
--rc-host=\"localhost\"
:\"4222\" --rc-quiet

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

8:


C:\TraktForVLC\windows_batch>cd /D "C:\TraktForVLC\windows_batch\"

C:\TraktForVLC\windows_batch>call ".\config.bat"

C:\TraktForVLC\windows_batch>set python="C:\Program Files\Python
3.5\pythonw.exe
"

C:\TraktForVLC\windows_batch>set tfv_py=C:\TraktForVLC\TraktForVLC.py

C:\TraktForVLC\windows_batch>set tfv_data=C:\TraktForVLC

C:\TraktForVLC\windows_batch>set tfv_config=C:\TraktForVLC\

C:\TraktForVLC\windows_batch>set tfv_pidfile=C:\TraktForVLC\TraktForVLC.pid

C:\TraktForVLC\windows_batch>set vlc_path=C:\Program Files
(x86)\VideoLAN\VLC\vl
c.exe

C:\TraktForVLC\windows_batch>set ip=localhost

C:\TraktForVLC\windows_batch>set port=4222

C:\TraktForVLC\windows_batch>set formats=avi, mkv, mov, mp4, wmv, ts, mpg

C:\TraktForVLC\windows_batch>set vlc_opts=--extraintf=rc
--rc-host=\"localhost\"
:\"4222\" --rc-quiet

C:\TraktForVLC\windows_batch>pause
Press any key to continue . . .

**Comment by bluishmatt** [comment]
I deleted all of my traktforvlc folder and downloaded a new one, made the
adjustments and retried and I didnt get that error about the directory..

**Comment by bluishmatt** [comment]
Updated the start and end process bats with the same:

@echo off

:: Change current directory to the directory where we have out batch file
cd /D %~dp0

:: Load configuration file for the path needed
call ".\config.bat"

updated the config.ini.default with my information (Do I need to delete the
'default'?)

changed:

Timer = 30
StartWatching = 10
ScrobblePercent = 2

so I only have to watch 2 percent, but it doesn't seem to do anything:/ the
vlc console shows my editing the volume. the episode is 42 minutes long and
I watch 1 minute which is more than 2 percent. The vlc console does nothing
and there's no changed in my trakt account. Any ideas?

**Comment by XaF** [comment]
Ok, so I guess the leftover issue was due to remanent files or something like that on your system. I'll consider that the commits to correct the quotes escapations will close that issue.

For your new situation, the ```config.ini.default``` file has to be copied to ```config.ini``` before being edited (the "default" file is part of TraktForVLC and will be erased if you want to paste on it the files of newer versions for instance). The ```config.ini.default``` is also not read by TraktForVLC, which will try to read the ```config.ini``` to start. I think that would be your current solution!

Also, if you have a problem running TraktForVLC, look at the last logfile to see if there is any error. If you can correct it (I guess in this case it will just tell you it didn't find the config file ?) perfect, but if you can't, you can create a new issue with a paste of a DEBUG logfile that you can generate by running TraktForVLC with ```--debug``` and ```--small-timers``` options! I would be happy to help you in such case! :) A new issue related to your exact problem will also be more helpful for future users that could have the same problem.

Thanks again for the time you took to help me correct that Windows issue, too!
