### ISSUE TITLE
README: weird links & outdated info

### ISSUE THREAD

**Issue by kerstin** [XaF/TraktForVLC#80]
Taking a closer look at the README, I noticed some links are oddly formatted, possibly because the README used to be of a different file type or due to a bad copy/paste job?

e.g. 
After the first [trakt.tv] [1](https://trakt.tv/) connection
instead of
After the first [trakt.tv](https://trakt.tv/) connection

Do you mind if I correct those?

Related to #77: should the README reflect that `--debug` mode won't produce a debug log anymore (like you mentioned in the other issue)? The way the README is worded right now it suggests it still does.

**Comment by XaF** [comment]
If you want to go ahead and fix it, I don't mind at all!
The README was written in Markdown, but GitHub decided to change the way it parsed Markdown at some point... I did not get the chance to fix that.

You can also fix the part for the --debug command.

I'm currently juggling with a lot of things, including the rewriting of `TraktForVLC` to be easier to maintain and improve (which is unfortunately not my priority, even if it's in the right direction). So I may not be overreactive at the moment... Sorry for that! :)

**Comment by XaF** [comment]
Click on the Travis information, it will direct you to your PR's builds. You can then check what is Travis complaining about... Sometimes it can be a pain. (I also need to improve the tests...)

**Comment by kerstin** [comment]
@XaF I'm suspecting Travis failing might have to do with the tests? Both #81 and #82 only contain changes to the README, and while the former passed, the latter failed. Which... doesn't really make sense, right?

**Comment by kerstin** [comment]
@XaF Any update on this?

According to the Travis logs, the builds seem to (sometimes) be failing because of `test_avengers` in `test_movie_info.py`, which was already part of the repo and which I didn't touch/which my PRs don't have anything to do with... This is true for #82 and apparently also the previous PRs I sent.

**Comment by kerstin** [comment]
Ping, @XaF.

Please tell me what I can do to fix my PRs. Don't want them rejected as they are part of my submissions for this year's Hacktoberfest also. (:

**Comment by XaF** [comment]
@kerstin I actually did not have time to include your PRs as other parts of TraktForVLC were broken... It thus did not make sense to create a new 1.x release while the 2.x was in development to replace everything. Sorry for that, I did not manage that properly ;(

TraktForVLC 2.x makes that issue obsolete - #88

**Comment by kerstin** [comment]
@XaF Hi, I was not aware you were working on a new version - that's cool to hear!

Still, I think letting (would-be) contributors know that you're working on an update in the background aka **communication** is essential as OS maintainer. A simple reply stating so really would suffice; not knowing if a project was abandoned and learning any contributions/time invested are "lost" efforts can be frustrating and off-putting (also in a general way, regarding OS).

**Comment by XaF** [comment]
Hi @kerstin,

You're totally right. And I had no intention of abandoning the previous version at first. TraktForVLC v2 was not at all in the form it is right now, and I still have a v2 branch that was ready to include your changes. However changes in VLC 3 broke a lot of things in TraktForVLC that precipitated a change of course, and given my limited time I was not sure at all of a timeline for the new version. I started replying with information regarding a new version in development to new PR/issues that were created after this work started. Unfortunately, yours was before then. I am really sorry for the situation: as I said in two different thread of yours, I did not manage it in the best of ways.

**Comment by kerstin** [comment]
Hey @XaF, thanks for explaining. Maybe best filed under "to avoid in future".

I'm definitely looking forward to trying the new version in any case – having to add scrobbles to Trakt manually is inconvenient (and unreliable if not done right away). (;

**Comment by XaF** [comment]
Please do and tell me if you are experiencing any issue! :)
