### ISSUE TITLE
Compatibility with VLC 3.0

### ISSUE THREAD

**Issue by Francis2b** [XaF/TraktForVLC#86]
It looks like TraktForVLC is broken with VLC 3.0. Is it just me?
Nothing is scrobbled when I play a movie or a TV show.
I update VLC to 3.0, re-configure it, restart my mac but nothing is scrobbled :(

Here is my log:

2018-02-12 14:36:55,596::TraktForVLC::INFO::Listening VLC to localhost:4222
2018-02-12 14:36:55,598::TraktForVLC::INFO::Could not find VLC running at localhost:4222

It looks like TraktForVLC can't find VLC running

Edit: I tried opening the log file, unload TraktForVLC and reload it while VLC was runing and it appeared TraktForVLC wasn't able to detect VLC. 
Is it possible that TraktForVLC is looking for VLC by is PID and this PID changed in the last VLC update? If so it might explain the issue

**Comment by Dimsok** [comment]
I don't think it's work now (for movie at least) on any version. On 2.2.6 it can't find movie too.

**Comment by XaF** [comment]
It's highly possible.
That's why I'm trying to get the TraktForVLC 2.0.0 out as soon as possible. Still needs work though...

**Comment by Francis2b** [comment]
@XaF If you need beta tester or any kind of help feel free to ask me ;)

**Comment by hexum311ad** [comment]
sam here

**Comment by XaF** [comment]
Should be solved TraktForVLC 2.x - #88
